# Generated by Django 5.2.6 on 2025-10-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MatrixTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row1", models.TextField(default="3")),
                ("column1", models.TextField(default="3")),
                ("row2", models.TextField(default="3")),
                ("column2", models.TextField(default="1")),
            ],
        ),
    ]
