# Generated by Django 5.2.6 on 2025-10-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matrix", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matrixtable",
            name="column1",
            field=models.CharField(default="3"),
        ),
        migrations.AlterField(
            model_name="matrixtable",
            name="column2",
            field=models.CharField(default="1"),
        ),
        migrations.AlterField(
            model_name="matrixtable",
            name="row1",
            field=models.CharField(default="3"),
        ),
        migrations.AlterField(
            model_name="matrixtable",
            name="row2",
            field=models.CharField(default="3"),
        ),
    ]
