# Generated by Django 5.2.6 on 2025-10-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matrix", "0004_table21_table22_table23_table24_table25_table31_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matrixtable",
            old_name="table1_row_column_21",
            new_name="row_column_21_table",
        ),
        migrations.RenameField(
            model_name="matrixtable",
            old_name="table1_row_column_22",
            new_name="row_column_22_table",
        ),
        migrations.RenameField(
            model_name="matrixtable",
            old_name="table1_row_column_23",
            new_name="row_column_23_table",
        ),
        migrations.RenameField(
            model_name="matrixtable",
            old_name="table1_row_column_24",
            new_name="row_column_24_table",
        ),
        migrations.RenameField(
            model_name="matrixtable",
            old_name="table1_row_column_25",
            new_name="row_column_25_table",
        ),
        migrations.RenameField(
            model_name="matrixtable",
            old_name="table1_row_column_31",
            new_name="row_column_31_table",
        ),
        migrations.RenameField(
            model_name="matrixtable",
            old_name="table1_row_column_32",
            new_name="row_column_32_table",
        ),
        migrations.RenameField(
            model_name="matrixtable",
            old_name="table1_row_column_33",
            new_name="row_column_33_table",
        ),
        migrations.RenameField(
            model_name="matrixtable",
            old_name="table1_row_column_34",
            new_name="row_column_34_table",
        ),
        migrations.RenameField(
            model_name="matrixtable",
            old_name="table1_row_column_35",
            new_name="row_column_35_table",
        ),
        migrations.RenameField(
            model_name="matrixtable",
            old_name="table1_row_column_41",
            new_name="row_column_41_table",
        ),
        migrations.RenameField(
            model_name="matrixtable",
            old_name="table1_row_column_42",
            new_name="row_column_42_table",
        ),
        migrations.RenameField(
            model_name="matrixtable",
            old_name="table1_row_column_43",
            new_name="row_column_43_table",
        ),
        migrations.RenameField(
            model_name="matrixtable",
            old_name="table1_row_column_44",
            new_name="row_column_44_table",
        ),
        migrations.RenameField(
            model_name="matrixtable",
            old_name="table1_row_column_45",
            new_name="row_column_45_table",
        ),
        migrations.RenameField(
            model_name="matrixtable",
            old_name="table1_row_column_52",
            new_name="row_column_52_table",
        ),
        migrations.RenameField(
            model_name="matrixtable",
            old_name="table1_row_column_53",
            new_name="row_column_53_table",
        ),
        migrations.RenameField(
            model_name="matrixtable",
            old_name="table1_row_column_54",
            new_name="row_column_54_table",
        ),
        migrations.RenameField(
            model_name="matrixtable",
            old_name="table1_row_column_55",
            new_name="row_column_55_table",
        ),
        migrations.RemoveField(
            model_name="matrixtable",
            name="table1_row_column_51",
        ),
        migrations.AddField(
            model_name="matrixtable",
            name="row_column_51_table",
            field=models.ManyToManyField(to="matrix.table51"),
        ),
    ]
