# Generated by Django 5.2.6 on 2025-10-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "matrix",
            "0005_rename_table1_row_column_21_matrixtable_row_column_21_table_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="table33",
            old_name="row3column3",
            new_name="row3_column3",
        ),
    ]
