# Generated by Django 5.2.6 on 2025-10-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matrix", "0006_rename_row3column3_table33_row3_column3"),
    ]

    operations = [
        migrations.RenameField(
            model_name="table43",
            old_name="row3column3",
            new_name="row3_column3",
        ),
        migrations.RenameField(
            model_name="table43",
            old_name="row4column3",
            new_name="row4_column3",
        ),
        migrations.RenameField(
            model_name="table53",
            old_name="row3column3",
            new_name="row3_column3",
        ),
        migrations.RenameField(
            model_name="table53",
            old_name="row4column3",
            new_name="row4_column3",
        ),
    ]
